<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'uitleg_' => 'Transactie toevoegen.',
    'uitleg_3' => 'Het gaat om overschrijvingen die een gebruiker van zijn eigen rekening heeft gemaakt.
            Het het gaat niet om de uitbetalingen die gemaakt zijn door Mollie of Izettle.',
    'uitleg_5','Als iemand inkopen heeft gedaan en zelf voorgeschoten heeft, dan kan dat hier ingevoerd worden.
            Het is verplicht om een bon in te voeren.
            De declaratie wordt verrekend met de rekening van de gebruiker. Als de gebruiker het geld terug wil dan kan dat.
            Het bedrag kan gewoon overgemaakt worden en kan dan ingevoerd worden als "Declaratie uitbetalen".
            Een declaratie die uitbetaald wordt, wordt ook automatisch weer met de rekening van de gebruiker verrekend.',
    'uitleg_6' => 'Als iemand statieflessen terug heeft gebracht, dan kan hij dat geld houden.
            Het bedrag van het statiegeld moet hier ingevoerd worden, dan wordt het verekend met de eerst voglende rekening.',
    'uitleg_7' => 'Hier moeten betalingen die zijn gedaan met de pinpas ingevoerd worden. Een bon is verplicht.',
    'uitleg_10' => 'Dit gaat om de pin betaling die een gebruiker heeft gedaan op het pin apparaat.',
    'uitleg_11' => 'Izettle doet maandelijks een uitbetaling. Het totale bedrag kan hier ingevoerd worden.
            Verder moeten de Izettle invoeren die hiermee uitbetaald worden, gelinkt worden.
            Omdat er meerdere transacties in 1 keer uitbetaald kunnen worden, hoeft er geen naam toegevoegd te worden.
            Verder moet een uitdraai van Izettle met een overzicht toegevoegd worden.',
    'uitleg_12' => 'Mollie doet maandelijks een uitbetaling. Het totale bedrag wat op de bankrekening bijgescreven wordt 
            moet hier ingevoerd worden. Verder moeten de Ideal betalingen die hiermee uitbetaald worden, gelinkt worden (dit kan ook nog later).
            <br>
            De PDF uitdraai van Mollie met een overzicht moet hier toegevoegd worden. Je kunt hier ook nog de kosten invoeren die Mollie rekent.
            Er wordt dan automatisch een kostenpost en een bon gemaakt.',
    'uitleg_13' => 'Als iemand een declaratie heeft gedaan, en het hele of gedeeltelijke bedrag terug wil hebben,
            dan kan de bank overschrijving hiet toegevoegd worden. De "Declaratie invoer" moet gelinkt worden.
            Want die heeft de orginele bon van de declaratie. Als er meerdere declaratie zijn ingevoerd,
            kunnen er ook meerdere gelinkt worden.',
    'uitleg_14' => 'De kosten die de ING rekent voor hun diensten
            Een afschrift invoeren is verplicht. Er wordt dan automatisch een kostenpost en een bon gemaakt.',
    'uitleg_15' => 'De kosten die Izettle rekent voor hun diensten
            De transactie van de uitbetaling moet gelinkt worden, want die heeft een uitdraai met ook de kosten',
    'uitleg_16' => 'De kosten die Mollie rekent voor hun diensten
            De transactie van de uitbetaling moet gelinkt worden, want die heeft een uitdraai met ook de kosten <br> <br>
            LET OP! deze post wordt automatisch aangemaakt als je de mollie uitbetaling goed invoerd! Dit formulier is 
            om eventuele correcties uit te voeren.',
    ];
